train:
  dev_directory: ./dev_data
  eval_directory: ./eval_data
  feature:
      frames: 5
      hop_length: 512
      n_fft: 1024
      n_mels: 128
      power: 2.0
      downsample: True
  fit:
      batch_size: 512
      compile:
        loss: mean_squared_error
        optimizer: adam
      epochs: 100
      shuffle: true
      validation_split: 0.1
      verbose: 1
  max_fpr: 0.1
  model:
      input_dim: 128
      batch_norm: true
      latent_dim: 8
      hidden_dim: 128
      l1reg: 0
      name: keras_model
      encode_depth: 4
      encode_in: 128
      decode_depth: 4
      decode_out: 128
      quantization:
          bits: f32
          int_bits: None
          last_bits: None
          last_int_bits: None
          relu_bits: None
          relu_int_bits: None
  model_directory: ./model/model_config/128input_4dense_64mels
  pruning:
      constant: false
      decay: false
      final_step: None
      initial_step: 0
      power: None
      sparsity: None
      initial_sparsity: None
      final_sparsity: None
  result_directory: ./result/model_config/128input_4dense_64mels
  result_file: result.csv