train:
  dev_directory: ./dev_data
  feature:
      frames: 5
      hop_length: 512
      n_fft: 1024
      n_mels: 128
      power: 2.0
      downsample: True
  fit:
      batch_size: 512
      compile:
        loss: mean_squared_error
        optimizer: adam
      epochs: 100
      shuffle: true
      validation_split: 0.1
      verbose: 1
  max_fpr: 0.1
  model:
      input_dim: 128
      batch_norm: true
      latent_dim: 8
      hidden_dim: 128
      l1reg: 0
      name: qkeras_model
      encode_depth: 1
      encode_in: 64
      decode_depth: 1
      decode_out: 64
      quantization:
          bits: 10
          int_bits: 0
          last_bits: 10
          last_int_bits: 10
          relu_bits: 5
          relu_int_bits: 5
  pruning:
      constant: false
      decay: false
      final_step: None
      initial_step: 0
      power: None
      sparsity: None
      initial_sparsity: None
      final_sparsity: None
  model_directory: ./model/model_config/ad03
  result_directory: ./result/test/model_config/ad03
  result_file: result.csv
convert:
  x_npy_plot_roc: test_data/anomaly_detection/downsampled_128_5_to_32_4_skip_method.npy
  y_npy_plot_roc: test_data/anomaly_detection/downsampled_128_5_to_32_4_ground_truths_skip_method.npy
  x_npy_hls_test_bench: ./test_data/anomaly_detection/test_bench/downsampled_128_5_to_32_4_skip_method.npy
  y_npy_hls_test_bench: ./test_data/anomaly_detection/test_bench/downsampled_128_5_to_32_4_ground_truths_skip_method.npy
  model_file: model/model_config/ad03/model_ToyCar.h5
  Build: True
  OutputDir: hls/results/config/ad03
  ClockPeriod: 10
  vivado_path: "/tools/Xilinx/Vivado/2019.1/bin:"
  Board: pynq-z2
  Trace: 0
  fpga_part: xc7z020clg400-1
  acc_name: anomaly_detection
  Backend: VivadoAccelerator
  IOType: io_stream
  Interface: axi_stream
  Driver: python
  Strategy: Resource
  HLSConfig:
    LayerName:
      batch_normalization:
        Precision:
          bias: ap_fixed<16,6>
          scale: ap_fixed<16,6>
        ReuseFactor: 4096
        Trace: true
        accum_t: ap_fixed<32,16>
      batch_normalization_1:
        Precision:
          bias: ap_fixed<16,6>
          scale: ap_fixed<16,6>
        ReuseFactor: 4096
        Trace: true
      batch_normalization_2:
        Precision:
          bias: ap_fixed<16,6>
          scale: ap_fixed<16,6>
        ReuseFactor: 4096
        Trace: true
      input_1:
        Precision: ap_fixed<8,8>
        Trace: true
      q_activation:
        Precision:
          result: ap_fixed<11,6>
        ReuseFactor: 4096
        Trace: true
        accum_t: ap_fixed<32,16>
      q_activation_1:
        Precision:
          result: ap_fixed<11,6>
        ReuseFactor: 4096
        Trace: true
      q_activation_2:
        Precision:
          result: ap_fixed<11,6>
        ReuseFactor: 4096
        Trace: true
      q_dense:
        Precision:
          bias: ap_fixed<11,1>
          weight: ap_fixed<11,1>
        ReuseFactor: 4096
        Trace: true
        accum_t: ap_fixed<32,16>
      q_dense_1:
        Precision:
          bias: ap_fixed<11,1>
          weight: ap_fixed<11,1>
        ReuseFactor: 4096
        Trace: true
        accum_t: ap_fixed<32,16>
      q_dense_2:
        Precision:
          bias: ap_fixed<11,1>
          weight: ap_fixed<11,1>
        ReuseFactor: 4096
        Trace: true
        accum_t: ap_fixed<32,16>
      q_dense_3:
        Precision:
          bias: ap_fixed<11,11>
          weight: ap_fixed<11,11>
        ReuseFactor: 4096
        Trace: true
        accum_t: ap_fixed<32,16>
    Model:
      Precision: ap_fixed<32,16>
      ReuseFactor: 4096
      Strategy: Resource
      FIFO_opt: False
