name: tiny
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - networkx=2.5=py_0
  - pip:
    - jupyter
    - pydot
    - graphviz
    - git+https://github.com/hls4ml-finn-mlperftiny/hls4ml.git
    - matplotlib
    - numpy
    - PyYAML
    - scikit-learn
    - tensorflow
    - tqdm
    - git+https://github.com/google/qkeras#egg=qkeras
    - keras-flops
    - git+https://github.com/kentaroy47/keras-Opcounter
    - keras-tuner
    - setgpu
    - mplhep
    - librosa==0.8.0
