LayerName:
  input_1:
    Precision: ap_fixed<8,8>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_activation:
    Precision:
      result: ap_ufixed<5,5>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
  q_activation_1:
    Precision:
      result: ap_ufixed<5,5>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
  q_activation_2:
    Precision:
      result: ap_ufixed<5,5>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
  q_activation_3:
    Precision:
      result: ap_ufixed<5,5>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
  q_activation_4:
    Precision:
      result: ap_ufixed<5,5>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
  q_dense:
    Precision:
      bias: ap_fixed<6,2>
      weight: ap_fixed<10,2>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_dense_linear:
    Precision:
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
  q_dense_batchnorm:
    Precision:
      bias: ap_fixed<17,7>
      weight: ap_fixed<17,7>
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_dense_batchnorm_linear:
    Precision:
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
  q_dense_batchnorm_1:
    Precision:
      bias: ap_fixed<15,5>
      weight: ap_fixed<15,5>
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_dense_batchnorm_1_linear:
    Precision:
      bias: ap_fixed<16,8>
      weight: ap_fixed<16,8>
  q_dense_batchnorm_2:
    Precision:
      bias: ap_fixed<15,5>
      weight: ap_fixed<15,5>
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_dense_batchnorm_2_linear:
    Precision:
      bias: ap_fixed<16,8>
      weight: ap_fixed<16,8>
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
  q_dense_batchnorm_3:
    Precision:
      bias: ap_fixed<16,6>
      weight: ap_fixed<16,6>
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_dense_batchnorm_3_linear:
    Precision:
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
  q_dense_batchnorm_4:
    Precision:
      bias: ap_fixed<15,5>
      weight: ap_fixed<15,5>
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>
    ReuseFactor: 16384
    Trace: true
    accum_t: ap_fixed<16,8>
  q_dense_batchnorm_4_linear:
    Precision:
      result: ap_fixed<16,8>
      default: ap_fixed<16,8>